# Generated by Django 4.0.4 on 2022-05-06 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SnippingAddress',
            new_name='ShippingAddress',
        ),
    ]
